"""init migrations

Revision ID: e906b8f2d1b5
Revises: 
Create Date: 2025-05-22 10:25:22.747830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e906b8f2d1b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('credor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('certidao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FEDERAL', 'STATE', 'MUNICIPAL', 'LABOR', name='entitytype'), nullable=False),
    sa.Column('origem', sa.Enum('MANUAL', 'API', name='dataorigin'), nullable=False),
    sa.Column('arquivo_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEGATIVE', 'POSITIVE', 'INVALID', 'PENDING', name='documentstatus'), nullable=False),
    sa.Column('recebida_em', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_pessoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('IDENTIDADE', 'COMPROVANTE_RESIDENCIA', 'ETC', name='personaldocumentenum'), nullable=False),
    sa.Column('arquivo_url', sa.String(), nullable=True),
    sa.Column('enviado_em', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('numero_precatorio', sa.String(), nullable=False),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('foro', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precatorio')
    op.drop_table('documento_pessoal')
    op.drop_table('certidao')
    op.drop_table('credor')
    op.drop_table('users')
    # ### end Alembic commands ###
